### ISSUE TITLE
Place A Link to The Paper on The Main Page

### ISSUE THREAD

**Issue by ilyaigpetrov** [datproject/datproject.org#25]
A link to https://datproject.org/paper should be placed somewhere on https://datproject.org, e.g. under "Learn" bottom section.

**Comment by joehand** [comment]
Hmm ya. I understand why that may be helpful - we used to link to the paper but replaced it with datprotocol.com. The paper is outdated/incomplete in areas, being replaced by active specifications on Dat Protocol site. So I am hesitant to link directly to it, since we'd rather direct folks to the correct/active specifications.

We're adding the paper link to the datprotocol.com site: https://deploy-preview-13--datprotocol.netlify.com/. Do you think that is sufficient?

**Comment by ilyaigpetrov** [comment]
People will be seeking for an overview of dat protocol and "Dat Protocol" link feels like a specification not an overview. Dat paper gives something like an overview even if it's outdated. If you have something better as an overview then put it forward in the bottom as "Dat overview", if you think there is nothing better than a paper for this then you may put it as "Dat paper (details are outdated)".
