### ISSUE TITLE
integration tests!

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#395]
- [x] registering an account
- [x] logging in 
- [x] registering with a name  not on the whitelist
- [x] publishing a dat
- [x] viewing the dat i just published
- [x] viewing the dat i just published in my user profile list

**Comment by yoshuawuyts** [comment]
@karissa how were you thinking of implementing this? In the past I've tried:
- saucelabs: tunneling is unreliable and drops out regularly
- electron-renderer: takes a long time to spawn, not great for local rendering

Asking because if we find something that works, we should probably use it for the desktop + choo too (noticed regressions popping up in the latter, unforch :cry:)

**Comment by karissa** [comment]
I'm a fan of saucelabs but since we are only worried about chrome and firefox we are using selenium. Check out tests/e2e. I'd rather not reuse tests because the functionality is easier to change then

**Comment by karissa** [comment]
If the element is shared we can share the tests though!

**Comment by yoshuawuyts** [comment]
Oh yeah no worries, was just wondering about approach is all 😁 - thanks
for answering!
