### ISSUE TITLE
Add browser to front page

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#538]
On the main page there is no way to know that you can access or preview dats from the browser given your own key, any ideas on that one?  It's kind of inferred from the demo dats, but maybe this could be more clear..

**Comment by Kriesse** [comment]
Yup, I'd love to fix this too! I think the two navigations have to be merged, so that install/access/import etc can be easily accessed from anywhere.

Current state:
![image](https://cloud.githubusercontent.com/assets/53684/26320410/17cf96dc-3f23-11e7-843d-0cfa8f9f5d46.png)

![image](https://cloud.githubusercontent.com/assets/53684/26320428/21ed434e-3f23-11e7-907a-daa95653bf6f.png)

@karissa Can we merge PRs #534 and #540? That would help me to start working on this, as they have some style/markup updates that affect the header.

**Comment by karissa** [comment]
Yeah, merged!

I agree that the two headers ought to be merged

**Comment by joehand** [comment]
Headers are merged!
